// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyhQBu2zDcbB_ucGzSaTBUMAIgQVeqBoI',
    appId: '1:46657008438:web:4fd5fcfd62ad456002b997',
    messagingSenderId: '46657008438',
    projectId: 'cartify-project',
    authDomain: 'cartify-project.firebaseapp.com',
    storageBucket: 'cartify-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIfwoAMTXXG-5Q1fD7UrkkzW8c6VGn3a0',
    appId: '1:46657008438:android:eb7b692bcd485eab02b997',
    messagingSenderId: '46657008438',
    projectId: 'cartify-project',
    storageBucket: 'cartify-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC90qZnyTTHDrffcyfn9vFSs0mkwT8eOs',
    appId: '1:46657008438:ios:16930bb2a970809902b997',
    messagingSenderId: '46657008438',
    projectId: 'cartify-project',
    storageBucket: 'cartify-project.appspot.com',
    iosBundleId: 'com.example.cartifyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC90qZnyTTHDrffcyfn9vFSs0mkwT8eOs',
    appId: '1:46657008438:ios:16930bb2a970809902b997',
    messagingSenderId: '46657008438',
    projectId: 'cartify-project',
    storageBucket: 'cartify-project.appspot.com',
    iosBundleId: 'com.example.cartifyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyhQBu2zDcbB_ucGzSaTBUMAIgQVeqBoI',
    appId: '1:46657008438:web:bcdb3ebcd04d711502b997',
    messagingSenderId: '46657008438',
    projectId: 'cartify-project',
    authDomain: 'cartify-project.firebaseapp.com',
    storageBucket: 'cartify-project.appspot.com',
  );
}
